server:
  port: 8082



logging:
  level:
    org.springframework.security: DEBUG
    log4j.logger.org.hibernate.SQL: DEBUG
    com.techolution: DEBUG
    
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://10.26.0.3:3306/mauritius_smartwater
    username: admin
    password: admin123
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-active: 5
    hikari:
      maximum-pool-size: 5
    application:
      name: consolidateddetailsservice
      
  data:
    redis:
      repositories:
        enabled: true
#  redis:
#    host: redis
#    port: 6379 
#    timeout:
#      seconds: 3600
      
 
influx:
    url: http://34.66.131.198:8086
    username: root
    password: root
    dbname: mauritius_smartwater_uat
    datatimezone: Indian/Mauritius 


  
